apiVersion: v1
kind: Service
metadata:
  name: network-tcp
spec:
  ports:
  - name: node
    port: 31236
    targetPort: 31236
  - name: graphql
    port: 31237
    targetPort: 31237
  - port: 6000
    name: gossip
    targetPort: 6000
  selector:
    app: internal-seed-tcp
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: seed-pow
spec:
  ports:
  - name: node
    port: 31236
    targetPort: 31236
  - name: graphql
    port: 31237
    targetPort: 31237
  - port: 6000
    name: gossip
    targetPort: 6000
  selector:
    app: internal-seed-pow
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: explorer
spec:
  ports:
  - port: 31235
    targetPort: 31235
  selector:
    app: explorer
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: internal-miner-1
spec:
  ports:
  - port: 80
    name: graphql
    targetPort: 80
  selector:
    app: internal-miner-1
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: internal-validator-1
spec:
  ports:
  - port: 80
    name: graphql
    targetPort: 80
  - port: 6000
    name: gossip
    targetPort: 6000
  - port: 31234
    name: swarm
    targetPort: 31234
  selector:
    app: internal-validator-1
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: internal-validator-2
spec:
  ports:
  - port: 80
    name: graphql
    targetPort: 80
  - port: 6000
    name: gossip
    targetPort: 6000
  - port: 31234
    name: swarm
    targetPort: 31234
  selector:
    app: internal-validator-2
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: internal-validator-3
spec:
  ports:
  - port: 80
    name: graphql
    targetPort: 80
  - port: 6000
    name: gossip
    targetPort: 6000
  - port: 31234
    name: swarm
    targetPort: 31234
  selector:
    app: internal-validator-3
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: internal-validator-4
spec:
  ports:
  - port: 80
    name: graphql
    targetPort: 80
  - port: 6000
    name: gossip
    targetPort: 6000
  - port: 31234
    name: swarm
    targetPort: 31234
  selector:
    app: internal-validator-4
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: internal-validator-5
spec:
  ports:
  - port: 80
    name: graphql
    targetPort: 80
  - port: 6000
    name: gossip
    targetPort: 6000
  - port: 31234
    name: swarm
    targetPort: 31234
  selector:
    app: internal-validator-5
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: internal-validator-6
spec:
  ports:
  - port: 80
    name: graphql
    targetPort: 80
  - port: 6000
    name: gossip
    targetPort: 6000
  - port: 31234
    name: swarm
    targetPort: 31234
  selector:
    app: internal-validator-6
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: internal-validator-7
spec:
  ports:
  - port: 80
    name: graphql
    targetPort: 80
  - port: 6000
    name: gossip
    targetPort: 6000
  - port: 31234
    name: swarm
    targetPort: 31234
  selector:
    app: internal-validator-7
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: internal-validator-8
spec:
  ports:
  - port: 80
    name: graphql
    targetPort: 80
  - port: 6000
    name: gossip
    targetPort: 6000
  - port: 31234
    name: swarm
    targetPort: 31234
  selector:
    app: internal-validator-8
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: internal-validator-9
spec:
  ports:
  - port: 80
    name: graphql
    targetPort: 80
  - port: 6000
    name: gossip
    targetPort: 6000
  - port: 31234
    name: swarm
    targetPort: 31234
  selector:
    app: internal-validator-9
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: internal-validator-10
spec:
  ports:
  - port: 80
    name: graphql
    targetPort: 80
  - port: 6000
    name: gossip
    targetPort: 6000
  - port: 31234
    name: swarm
    targetPort: 31234
  selector:
    app: internal-validator-10
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: internal-validator-11
spec:
  ports:
  - port: 80
    name: graphql
    targetPort: 80
  - port: 6000
    name: gossip
    targetPort: 6000
  - port: 31234
    name: swarm
    targetPort: 31234
  selector:
    app: internal-validator-11
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: internal-validator-12
spec:
  ports:
  - port: 80
    name: graphql
    targetPort: 80
  - port: 6000
    name: gossip
    targetPort: 6000
  - port: 31234
    name: swarm
    targetPort: 31234
  selector:
    app: internal-validator-12
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: headless-admin
spec:
  ports:
  - name: graphql
    port: 80
    targetPort: 80
  - name: headless
    port: 31234
    targetPort: 31234
  selector:
    app: headless-admin
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: remote-headless-1
spec:
  ports:
  - name: graphql
    port: 80
    targetPort: 80
  - name: rpc
    port: 31238
    targetPort: 31238
  - name: headless
    port: 31234
    targetPort: 31234
  selector:
    app: remote-headless-1
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: internal-data-provider
spec:
  ports:
    - name: headless
      port: 31234
      targetPort: 31234
    - name: graphql
      port: 80
      targetPort: 80
  selector:
    app: internal-data-provider
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: internal-data-provider-db
  name: internal-data-provider-db
spec:
  ports:
    - name: "3306"
      port: 3306
      targetPort: 3306
  selector:
    app: internal-data-provider-db
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: pbftstats
spec:
  ports:
  - name: "http"
    port: 80
    targetPort: 80
  selector:
    app: pbftstats
  type: LoadBalancer

---
